const offers = [
  {
    name: `Beautiful &amp; luxurious studio at great location`,
    rating: `4.8`,
    imageSrc: `../../img/apartment-01.jpg`,
    features: [`Entire place`, `3 Bedrooms`, `Max 4 adults`],
    price: `120`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [52.3909553943508, 4.85309666406198],
    city: `Amsterdam`,
  },
  {
    name: `Wood and stone place`,
    rating: `5`,
    imageSrc: `../../img/apartment-02.jpg`,
    features: [`Entire place`, `4 Bedrooms`, `Max 6 adults`],
    price: `80`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [52.369553943508, 4.85309666406198],
    city: `Amsterdam`,
  },
  {
    name: `Canal View Prinsengracht`,
    rating: `3.8`,
    imageSrc: `../../img/apartment-03.jpg`,
    features: [`Entire place`, `1 Bedrooms`, `Max 2 adults`],
    price: `132`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [52.3909553943508, 4.929309666406198],
    city: `Amsterdam`,
  },
  {
    name: `Nice, cozy, warm big bed apartment`,
    rating: `4.9`,
    imageSrc: `../../img/apartment-01.jpg`,
    features: [`Entire place`, `2 Bedrooms`, `Max 4 adults`],
    price: `180`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [52.3809553943508, 4.939309666406198],
    city: `Amsterdam`,
  },
  {
    name: `Beautiful &amp; luxurious studio at great location`,
    rating: `4.8`,
    imageSrc: `../../img/apartment-01.jpg`,
    features: [`Entire place`, `3 Bedrooms`, `Max 4 adults`],
    price: `120`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [48.8709553943508, 2.36],
    city: `Paris`,
  },
  {
    name: `Wood and stone place`,
    rating: `5`,
    imageSrc: `../../img/apartment-02.jpg`,
    features: [`Entire place`, `4 Bedrooms`, `Max 6 adults`],
    price: `80`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [48.8766, 2.3522],
    city: `Paris`,
  },
  {
    name: `Canal View Prinsengracht`,
    rating: `3.8`,
    imageSrc: `../../img/apartment-03.jpg`,
    features: [`Entire place`, `1 Bedrooms`, `Max 2 adults`],
    price: `132`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [48.8566, 2.3422],
    city: `Paris`,
  },
  {
    name: `Nice, cozy, warm big bed apartment`,
    rating: `4.9`,
    imageSrc: `../../img/apartment-01.jpg`,
    features: [`Entire place`, `2 Bedrooms`, `Max 4 adults`],
    price: `180`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [48.8566, 2.3572],
    city: `Paris`,
  },
  {
    name: `Beautiful &amp; luxurious studio at great location`,
    rating: `4.8`,
    imageSrc: `../../img/apartment-01.jpg`,
    features: [`Entire place`, `3 Bedrooms`, `Max 4 adults`],
    price: `120`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [50.9375, 6.9603],
    city: `Cologne`,
  },
  {
    name: `Wood and stone place`,
    rating: `5`,
    imageSrc: `../../img/apartment-02.jpg`,
    features: [`Entire place`, `4 Bedrooms`, `Max 6 adults`],
    price: `80`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [50.9375, 6.9703],
    city: `Cologne`,
  },
  {
    name: `Canal View Prinsengracht`,
    rating: `3.8`,
    imageSrc: `../../img/apartment-03.jpg`,
    features: [`Entire place`, `1 Bedrooms`, `Max 2 adults`],
    price: `132`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [50.9, 6.9603],
    city: `Cologne`,
  },
  {
    name: `Nice, cozy, warm big bed apartment`,
    rating: `4.9`,
    imageSrc: `../../img/apartment-01.jpg`,
    features: [`Entire place`, `2 Bedrooms`, `Max 4 adults`],
    price: `180`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [50.89475, 6.9703],
    city: `Cologne`,
  },
  {
    name: `Beautiful &amp; luxurious studio at great location`,
    rating: `4.8`,
    imageSrc: `../../img/apartment-01.jpg`,
    features: [`Entire place`, `3 Bedrooms`, `Max 4 adults`],
    price: `120`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [50.8603, 4.3517],
    city: `Brussels`,
  },
  {
    name: `Wood and stone place`,
    rating: `5`,
    imageSrc: `../../img/apartment-02.jpg`,
    features: [`Entire place`, `4 Bedrooms`, `Max 6 adults`],
    price: `80`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [50.8503, 4.3517],
    city: `Brussels`,
  },
  {
    name: `Canal View Prinsengracht`,
    rating: `3.8`,
    imageSrc: `../../img/apartment-03.jpg`,
    features: [`Entire place`, `1 Bedrooms`, `Max 2 adults`],
    price: `132`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [50.8503, 4.3617],
    city: `Brussels`,
  },
  {
    name: `Nice, cozy, warm big bed apartment`,
    rating: `4.9`,
    imageSrc: `../../img/apartment-01.jpg`,
    features: [`Entire place`, `2 Bedrooms`, `Max 4 adults`],
    price: `180`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [50.85603, 4.3617],
    city: `Brussels`,
  },
  {
    name: `Beautiful &amp; luxurious studio at great location`,
    rating: `4.8`,
    imageSrc: `../../img/apartment-01.jpg`,
    features: [`Entire place`, `3 Bedrooms`, `Max 4 adults`],
    price: `120`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [53.5511, 9.9937],
    city: `Hamburg`,
  },
  {
    name: `Wood and stone place`,
    rating: `5`,
    imageSrc: `../../img/apartment-02.jpg`,
    features: [`Entire place`, `4 Bedrooms`, `Max 6 adults`],
    price: `80`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [53.5611, 9.9937],
    city: `Hamburg`,
  },
  {
    name: `Canal View Prinsengracht`,
    rating: `3.8`,
    imageSrc: `../../img/apartment-03.jpg`,
    features: [`Entire place`, `1 Bedrooms`, `Max 2 adults`],
    price: `132`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [53.5511, 9.9977],
    city: `Hamburg`,
  },
  {
    name: `Nice, cozy, warm big bed apartment`,
    rating: `4.9`,
    imageSrc: `../../img/apartment-01.jpg`,
    features: [`Entire place`, `2 Bedrooms`, `Max 4 adults`],
    price: `180`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [53.5611, 9.9967],
    city: `Hamburg`,
  },
  {
    name: `Beautiful &amp; luxurious studio at great location`,
    rating: `4.8`,
    imageSrc: `../../img/apartment-01.jpg`,
    features: [`Entire place`, `3 Bedrooms`, `Max 4 adults`],
    price: `120`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [51.2277, 6.7735],
    city: `Dusseldorf`,
  },
  {
    name: `Wood and stone place`,
    rating: `5`,
    imageSrc: `../../img/apartment-02.jpg`,
    features: [`Entire place`, `4 Bedrooms`, `Max 6 adults`],
    price: `80`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [51.2377, 6.7735],
    city: `Dusseldorf`,
  },
  {
    name: `Canal View Prinsengracht`,
    rating: `3.8`,
    imageSrc: `../../img/apartment-03.jpg`,
    features: [`Entire place`, `1 Bedrooms`, `Max 2 adults`],
    price: `132`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [51.2477, 6.7735],
    city: `Dusseldorf`,
  },
  {
    name: `Nice, cozy, warm big bed apartment`,
    rating: `4.9`,
    imageSrc: `../../img/apartment-01.jpg`,
    features: [`Entire place`, `2 Bedrooms`, `Max 4 adults`],
    price: `180`,
    inside: [`Wi-Fi`, `Washing machine`, `Towels`, `Heating`, `Coffee machine`, `Baby seat`, `Kitchen`, `Dishwasher`, `Cabel TV`, `Fridge`],
    description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    hostName: `Angelina`,
    coords: [51.2577, 6.7735],
    city: `Dusseldorf`,
  },
];

export default offers;
